#!/bin/bash
######Create Users
/usr/sbin/groupadd -g 713 mdware ;  /usr/sbin/useradd -g mdware tomcat;
######Create required directories
mkdir -p /apps/opt/incoming ; chmod 777 /apps/opt/incoming
######Set Proxy 
DOMAIN=$( hostname |cut -f2-4 -d. )
if [ $DOMAIN = 'ebiz.verizon.com' ]; then
    #nonprod
    HTTP_PROXY="http://proxy.ebiz.verizon.com:80/"
    HTTPS_PROXY="http://proxy.ebiz.verizon.com:80/"
    http_proxy="http://proxy.ebiz.verizon.com:80/"
    https_proxy="http://proxy.ebiz.verizon.com:80/"
    vz_proxy="proxy.ebiz.verizon.com"
    no_proxy=localhost.localdomain,169.254.169.254,verizon.com,ebiz.verizon.com,vpc.verizon.com
    export HTTP_PROXY HTTPS_PROXY http_proxy https_proxy no_proxy vz_proxy
elif [ $DOMAIN = 'vpc.verizon.com' ]; then
    #prod and staging
    HTTP_PROXY="http://vzproxy.verizon.com:80/"
    HTTPS_PROXY="http://vzproxy.verizon.com:80/"
    http_proxy="http://vzproxy.verizon.com:80/"
    https_proxy="http://vzproxy.verizon.com:80/"
    vz_proxy="vzproxy.verizon.com"
    no_proxy=localhost.localdomain,169.254.169.254,verizon.com,ebiz.verizon.com,vpc.verizon.com
    export HTTP_PROXY HTTPS_PROXY http_proxy https_proxy no_proxy vz_proxy
fi
######Download & Install Packages
# JDK Install
curl -u SVC-CMB-INFRA-DEPLOY:dI16mC16rdI16mC16rdI16mC16rdI -o /apps/opt/incoming/VZjdk-1.8.0_172_b31_64bit-Linux.rpm https://oneartifactory.verizon.com/artifactory/VVOV_SSP/WILDFLY_PACKAGES/VZjdk-1.8.0_172_b31_64bit-Linux.rpm
rpm -ihv --ignorearch --ignoreos --nodeps /apps/opt/incoming/VZjdk-1.8.0_172_b31_64bit-Linux.rpm
# Set Java Path
export PATH=$PATH:`ls -d /apps/opt/jdk*/bin | tail -1`
##SetJavaPath in profile
echo -e "export PATH=$PATH:`ls -d /apps/opt/jdk*/bin | tail -1`" >> ~/.bash_profile
# Tomcat Install
wget -P /apps/opt/incoming http://apache.spinellicreations.com/tomcat/tomcat-8/v8.5.45/bin/apache-tomcat-8.5.45.tar.gz
#curl -v --proxy http://proxy.ebiz.verizon.com:80 --proxy-ntlm --proxy-user "VDSI\\v432155" -o /apps/opt/incoming/apache-tomcat-8.5.45.tar.gz http://apache.spinellicreations.com/tomcat/tomcat-8/v8.5.45/bin/apache-tomcat-8.5.45.tar.gz
tar -zxvf /apps/opt/incoming/apache-tomcat-8.5.45.tar.gz -C /apps/opt

# Install MySql
wget -P /apps/opt/incoming/ https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
yum install -y /apps/opt/incoming/mysql57-community-release-el7-9.noarch.rpm
yum-config-manager --disable base
yum install -y mysql-server
systemctl start mysqld
#systemctl status mysqld
temp_password=$(grep password /var/log/mysqld.log | awk '{print $NF}')
# Set up a batch file with the SQL commands
echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '9ol.>LO('; flush privileges;" > reset_pass.sql
# Log in to the server with the temporary password, and pass the SQL file to it.
mysql -u root --password="$temp_password" --connect-expired-password < reset_pass.sql
#Create user
echo -e "CREATE USER 'srini'@'localhost' IDENTIFIED BY '9ol.>LO(';
GRANT ALL PRIVILEGES ON *.* TO 'srini'@'localhost' WITH GRANT OPTION;
CREATE USER 'srini'@'%' IDENTIFIED BY '9ol.>LO(';
GRANT ALL PRIVILEGES ON *.* TO 'srini'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES; " > crtuser.sql
mysql -u root -p'9ol.>LO(' < crtuser.sql
